### ISSUE TITLE
Exception: Wrong Username/Password

### ISSUE THREAD

**Issue by we-do** [huacnlee/PokemonGoMove#35]
Though I am certainly using the correct login information it seems that there is some issue blocking me from logging in. My immediate suspicion is that since my GMAIL address uses a format of [ABC.DEF.GHI@GMAIL.COM] (with periods) that could be causing some sort of issue? 

```
[-] register_background_thread called
[-] register_background_thread: not running inside Flask so not starting thread
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
[-] register_background_thread called
[-] register_background_thread: initial registration
 * Debugger is active!
[+] Locale is en
[+] Getting initial location
 * Debugger pin code: 481-831-175
[!] Your given location: 123 Any Street, City, STATE 70000, USA
[!] lat/long/alt: 40.00000000-105.0000000 0.0
[!] Google login for: [example.example.example@gmail.com]
127.0.0.1 - - [20/Jul/2016 21:43:39] "GET /data HTTP/1.1" 200 -
Exception in thread search_thread:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "example.py", line 585, in main
    api_endpoint, access_token, profile_response = login(args)
  File "example.py", line 96, in memoizer
    cache[key] = obj(*args, **kwargs)
  File "example.py", line 520, in login
    raise Exception('[-] Wrong username/password')
Exception: [-] Wrong username/password

127.0.0.1 - - [20/Jul/2016 21:43:41] "GET /data HTTP/1.1" 200 -
127.0.0.1 - - [20/Jul/2016 21:43:43] "GET /data HTTP/1.1" 200 -
```

**Comment by fengyuhan** [comment]
remove the [] and try again

**Comment by we-do** [comment]
Derp. Works! TY

**Comment by fengyuhan** [comment]
@we-do hey, ur app able to move locations?

**Comment by we-do** [comment]
Yes, It all works as expected.
