### ISSUE TITLE
flask problems

### ISSUE THREAD

**Issue by baskettcase** [huacnlee/PokemonGoMove#48]
Im getting these messages and flask isn't working

The directory '/Users/username/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/username/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.

and

Traceback (most recent call last):
  File "example.py", line 4, in <module>
    import flask
ImportError: No module named flask

Ideas?

**Comment by mdemin914** [comment]
Running into the same issue running python example.py followed by the arguments. Mac OSX 10.11, Python 2.7.10, pip 8.1.2

Traceback (most recent call last):
  File "example.py", line 4, in <module>
    import flask
  File "/usr/local/lib/python2.7/site-packages/flask/__init__.py", line 17, in <module>
    from werkzeug.exceptions import abort
  File "/usr/local/lib/python2.7/site-packages/werkzeug/__init__.py", line 152, in <module>
    __import__('werkzeug.exceptions')
  File "/usr/local/lib/python2.7/site-packages/werkzeug/exceptions.py", line 71, in <module>
    from werkzeug.wrappers import Response
  File "/usr/local/lib/python2.7/site-packages/werkzeug/wrappers.py", line 26, in <module>
    from werkzeug.http import HTTP_STATUS_CODES, \
  File "/usr/local/lib/python2.7/site-packages/werkzeug/http.py", line 28, in <module>
    from urllib.request import parse_http_list as _parse_list_header
ImportError: No module named request

**Comment by Haar** [comment]
I'd suggest you use virtualenv for setting up the environment to run the script in.
Full details on virtualenv [here](http://docs.python-guide.org/en/latest/dev/virtualenvs/).

Cliffnotes:

``` bash
cd /path/to/PokemonGoMove/map
pip install virtualenv
virtualenv venv
source venv/bin/activate
pip install -r requirements.txt
python example.py "blah blah"
```

**Comment by baskettcase** [comment]
Ok that worked. Ill close this one and create a new issue since Im still having problems, just a different problem.
