### ISSUE TITLE
Wrong username/password error

### ISSUE THREAD

**Issue by fangliapple** [huacnlee/PokemonGoMove#65]
Hello!  I followed your instruction for Start web servers. But after i enter my google_address and google_password, it shows me an error of Wrong username/password .

I used hulipokemon@gmail.com and its password.  

Can you check it?  Thanks.

**Comment by adamroddick** [comment]
Do you have 2 Factor Auth enabled on your gmail account? You'll have to disable it if so.

**Comment by gwleuverink** [comment]
I seem to have the same problem. 2 factor auth is turned off.
The filled in are definitely correct. I get the following traceback:

```

[!] Google login for: [********@gmail.com]
Exception in thread search_thread:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "example.py", line 585, in main
    api_endpoint, access_token, profile_response = login(args)
  File "example.py", line 96, in memoizer
    cache[key] = obj(*args, **kwargs)
  File "example.py", line 520, in login
    raise Exception('[-] Wrong username/password')
Exception: [-] Wrong username/password


```

It seems google doesn't provide an auth key even tough my login details ar filled in correctly (checked them multiple times).
